<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [2]:
import pandas as pd

Load the dataset into a dataframe.

In [3]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [4]:
# your code goes here
print(len(df))
df_duplicate_rows = df.duplicated().sum()
print(df_duplicate_rows)

11552
154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [5]:
# your code goes here
print(len(df))
df.drop_duplicates(inplace=True)
print(len(df))

11552
11398

Verify if duplicates were actually dropped.

In [6]:
# your code goes here
EdLevel_nan_count = df['EdLevel'].isna().sum()
print(EdLevel_nan_count)

112

In [15]:
Country_nan_count = df['Country'].isna().sum()
print(Country_nan_count)

0

 What is the majority category under the column Employment?

In [17]:
print(df['Employment'].mode())

0    Employed full-time
dtype: object

In [18]:
UndergradMajor_ = df["UndergradMajor"].value_counts()
print(UndergradMajor_)

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

In [19]:
print(df["CompFreq"].unique())

['Yearly' 'Monthly' 'Weekly' nan]

In [20]:
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,11398.000000,1.058900e+04,1.058200e+04,11276.000000,8972.000000,11111.000000
mean,12490.392437,7.570477e+05,1.315967e+05,42.064606,4.781071,30.778895
std,7235.461999,9.705598e+06,2.947865e+05,24.672741,4.567060,7.393686
min,4.000000,0.000000e+00,0.000000e+00,3.000000,0.000000,16.000000
25%,6264.250000,2.500000e+04,2.686800e+04,40.000000,2.000000,25.000000
50%,12484.000000,6.500000e+04,5.774500e+04,40.000000,4.000000,29.000000
75%,18784.750000,1.200000e+05,1.000000e+05,43.000000,5.000000,35.000000
max,25142.000000,7.000000e+08,2.000000e+06,1012.000000,99.000000,99.000000

In [31]:
print(df)

       Respondent                      MainBranch Hobbyist  \
0               4  I am a developer by profession       No
1               9  I am a developer by profession      Yes
2              13  I am a developer by profession      Yes
3              16  I am a developer by profession      Yes
4              17  I am a developer by profession      Yes
...           ...                             ...      ...
11547       25136  I am a developer by profession      Yes
11548       25137  I am a developer by profession      Yes
11549       25138  I am a developer by profession      Yes
11550       25141  I am a developer by profession      Yes
11551       25142  I am a developer by profession      Yes

                                             OpenSourcer  \
0                                                  Never
1                             Once a month or more often
2      Less than once a month but more than once per ...
3                                                  Never
4      Less than once a month but more than once per ...
...                                                  ...
11547                                              Never
11548                                              Never
11549                            Less than once per year
11550  Less than once a month but more than once per ...
11551  Less than once a month but more than once per ...

                                              OpenSource          Employment  \
0      The quality of OSS and closed source software ...  Employed full-time
1      The quality of OSS and closed source software ...  Employed full-time
2      OSS is, on average, of HIGHER quality than pro...  Employed full-time
3      The quality of OSS and closed source software ...  Employed full-time
4      The quality of OSS and closed source software ...  Employed full-time
...                                                  ...                 ...
11547  OSS is, on average, of HIGHER quality than pro...  Employed full-time
11548  The quality of OSS and closed source software ...  Employed full-time
11549  The quality of OSS and closed source software ...  Employed full-time
11550  OSS is, on average, of LOWER quality than prop...  Employed full-time
11551  OSS is, on average, of HIGHER quality than pro...  Employed full-time

              Country Student  \
0       United States      No
1         New Zealand      No
2       United States      No
3      United Kingdom      No
4           Australia      No
...               ...     ...
11547   United States      No
11548          Poland      No
11549   United States      No
11550     Switzerland      No
11551  United Kingdom      No

                                                 EdLevel  \
0               Bachelor’s degree (BA, BS, B.Eng., etc.)
1      Some college/university study without earning ...
2            Master’s degree (MA, MS, M.Eng., MBA, etc.)
3            Master’s degree (MA, MS, M.Eng., MBA, etc.)
4               Bachelor’s degree (BA, BS, B.Eng., etc.)
...                                                  ...
11547        Master’s degree (MA, MS, M.Eng., MBA, etc.)
11548        Master’s degree (MA, MS, M.Eng., MBA, etc.)
11549        Master’s degree (MA, MS, M.Eng., MBA, etc.)
11550  Secondary school (e.g. American high school, G...
11551          Other doctoral degree (Ph.D, Ed.D., etc.)

                                          UndergradMajor  ...  \
0      Computer science, computer engineering, or sof...  ...
1      Computer science, computer engineering, or sof...  ...
2      Computer science, computer engineering, or sof...  ...
3                                                    NaN  ...
4      Computer science, computer engineering, or sof...  ...
...                                                  ...  ...
11547  Computer science, computer engineering, or sof...  ...
11548  Computer science, computer engineering, or sof...  ...
11549  Computer science, computer engineering, or sof...  ...
11550                                                NaN  ...
11551  A natural science (ex. biology, chemistry, phy...  ...

                                  WelcomeChange  \
0       Just as welcome now as I felt last year
1       Just as welcome now as I felt last year
2      Somewhat more welcome now than last year
3       Just as welcome now as I felt last year
4       Just as welcome now as I felt last year
...                                         ...
11547   Just as welcome now as I felt last year
11548     A lot more welcome now than last year
11549     A lot more welcome now than last year
11550  Somewhat less welcome now than last year
11551   Just as welcome now as I felt last year

                                            SONewContent   Age Gender Trans  \
0      Tech articles written by other developers;Indu...  22.0    Man    No
1                                                    NaN  23.0    Man    No
2      Tech articles written by other developers;Cour...  28.0    Man    No
3      Tech articles written by other developers;Indu...  26.0    Man    No
4      Tech articles written by other developers;Indu...  29.0    Man    No
...                                                  ...   ...    ...   ...
11547  Tech articles written by other developers;Cour...  36.0    Man    No
11548  Tech articles written by other developers;Tech...  25.0    Man    No
11549  Tech articles written by other developers;Indu...  34.0    Man    No
11550                                                NaN  25.0    Man    No
11551  Tech articles written by other developers;Tech...  30.0    Man    No

                     Sexuality                              Ethnicity  \
0      Straight / Heterosexual           White or of European descent
1                     Bisexual           White or of European descent
2      Straight / Heterosexual           White or of European descent
3      Straight / Heterosexual           White or of European descent
4      Straight / Heterosexual  Hispanic or Latino/Latina;Multiracial
...                        ...                                    ...
11547  Straight / Heterosexual           White or of European descent
11548  Straight / Heterosexual           White or of European descent
11549  Straight / Heterosexual           White or of European descent
11550  Straight / Heterosexual           White or of European descent
11551                 Bisexual           White or of European descent

      Dependents           SurveyLength                  SurveyEase
0             No  Appropriate in length                        Easy
1             No  Appropriate in length  Neither easy nor difficult
2            Yes  Appropriate in length                        Easy
3             No  Appropriate in length  Neither easy nor difficult
4             No  Appropriate in length                        Easy
...          ...                    ...                         ...
11547         No  Appropriate in length                   Difficult
11548         No  Appropriate in length  Neither easy nor difficult
11549        Yes               Too long                        Easy
11550         No  Appropriate in length                        Easy
11551         No  Appropriate in length                        Easy

[11398 rows x 85 columns]

## Finding Missing values

Find the missing values for all columns.

In [7]:

# for col in df.columns:
    # if col == 'Respondent':

print(df['Respondent'].duplicated().sum())

0

Find out how many rows are missing in the column 'WorkLoc'

In [8]:
# your code goes here

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [9]:
# your code goes here

Identify the value that is most frequent (majority) in the WorkLoc column.

In [10]:
#make a note of the majority value here, for future reference
#

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [11]:
# your code goes here

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [12]:
# your code goes here

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [13]:
# your code goes here

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [14]:
# your code goes here

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).